/* Native MC event viewer. Spatial coordinates are in GCD metres; no track magnification. */
'use strict';
const $ = id => document.getElementById(id);
const V = a => new THREE.Vector3(...a);
const SUBS = ['IceCube','DeepCore','Upgrade'];
const COLORS = {IceCube:0x5b7c9b,DeepCore:0x83adba,Upgrade:0x87cbbd};
const LABELS = {12:'νe',14:'νμ',16:'ντ'};
let geo, catalogue, metadata, current, matches=[], currentIndex=0, generation=0;
let playing=false, fraction=1, lastWall=0, tmin=0, tmax=1, hitRows=[], actors=[];
const stage=$('stage'), canvas=$('scene');
let renderer, scene, camera, orbit, hitGeometry, hitMesh;
const detectors={}, geology=new THREE.Group(), dust=new THREE.Group(), truth=new THREE.Group(), guide=new THREE.Group();
const dummyColor = new THREE.Color();

function setPlaying(value){playing=value;$('play').textContent=value?'Ⅱ':'▶';$('play').setAttribute('aria-label',value?'Pause event':'Play event');}
function fail(error){$('error').hidden=false;$('error').textContent=`Unable to load the viewer. ${error.message}. Please reload the page.`;console.error(error);}
async function getJSON(path){const response=await fetch(path);if(!response.ok)throw Error(`${path}: HTTP ${response.status}`);return response.json();}
function disposeGroup(group){group.traverse(obj=>{obj.geometry?.dispose();const materials=Array.isArray(obj.material)?obj.material:[obj.material];materials.forEach(m=>{m?.map?.dispose();m?.dispose();});});group.clear();}
function line(points,color,opacity=1,dashed=false){const material=dashed?new THREE.LineDashedMaterial({color,dashSize:12,gapSize:9,transparent:true,opacity}):new THREE.LineBasicMaterial({color,transparent:true,opacity});const object=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points.map(V)),material);if(dashed)object.computeLineDistances();return object;}
function points(positions,color,size,opacity=.7){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions.flat(),3));return new THREE.Points(geometry,new THREE.PointsMaterial({color,size,sizeAttenuation:false,transparent:true,opacity,depthWrite:false}));}
function textLabel(text,position){const c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=512;c.height=64;ctx.font='26px sans-serif';ctx.fillStyle='#aac3d4';ctx.textAlign='center';ctx.fillText(text,256,40);const material=new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false,sizeAttenuation:false});const sprite=new THREE.Sprite(material);sprite.position.copy(V(position));sprite.scale.set(.32,.04,1);return sprite;}

class Orbit {
 constructor(){this.target=new THREE.Vector3(35,-60,-350);this.radius=1100;this.theta=-1.1;this.phi=1.12;this.pointers=new Map();
  canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,[e.clientX,e.clientY]);};
  canvas.onpointerup=canvas.onpointercancel=e=>this.pointers.delete(e.pointerId);
  canvas.onpointermove=e=>{const old=this.pointers.get(e.pointerId);if(!old)return;
   if(this.pointers.size===2){const other=[...this.pointers.entries()].find(([id])=>id!==e.pointerId)[1];const before=Math.hypot(old[0]-other[0],old[1]-other[1]);const after=Math.hypot(e.clientX-other[0],e.clientY-other[1]);if(after>0)this.radius*=before/after;}
   else if(e.shiftKey||e.buttons===2){const scale=this.radius*.001;this.target.x-=(e.clientX-old[0])*scale*Math.sin(this.theta);this.target.y+=(e.clientX-old[0])*scale*Math.cos(this.theta);this.target.z+=(e.clientY-old[1])*scale;}
   else{this.theta-=(e.clientX-old[0])*.006;this.phi-= (e.clientY-old[1])*.006;}
   this.radius=Math.max(25,Math.min(12000,this.radius));this.phi=Math.max(.05,Math.min(Math.PI-.05,this.phi));this.pointers.set(e.pointerId,[e.clientX,e.clientY]);};
  canvas.oncontextmenu=e=>e.preventDefault();canvas.addEventListener('wheel',e=>{e.preventDefault();this.radius=Math.max(25,Math.min(12000,this.radius*Math.exp(e.deltaY*.0015)));},{passive:false});
 }
 update(){camera.position.set(this.target.x+this.radius*Math.sin(this.phi)*Math.cos(this.theta),this.target.y+this.radius*Math.sin(this.phi)*Math.sin(this.theta),this.target.z+this.radius*Math.cos(this.phi));camera.up.set(0,0,1);camera.lookAt(this.target);}
}
function initScene(){
 renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x080f19);
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(43,1,.1,20000);orbit=new Orbit();
 scene.add(geology,dust,truth,guide);
 for(const sub of SUBS){const group=new THREE.Group();detectors[sub]=group;scene.add(group);const modules=geo.modules.filter(m=>m[6]===sub);group.add(points(modules.map(m=>m.slice(2,5)),COLORS[sub],sub==='Upgrade'?2.6:2,.55));
  const strings=new Map();for(const m of modules){if(!strings.has(m[0]))strings.set(m[0],[]);strings.get(m[0]).push(m);}for(const modules of strings.values()){modules.sort((a,b)=>a[4]-b[4]);group.add(line([modules[0].slice(2,5),modules.at(-1).slice(2,5)],COLORS[sub],.19));}}
 buildGeology();
 hitGeometry=new THREE.BufferGeometry();const n=geo.modules.length;hitGeometry.setAttribute('position',new THREE.Float32BufferAttribute(geo.modules.flatMap(m=>m.slice(2,5)),3));hitGeometry.setAttribute('color',new THREE.Float32BufferAttribute(new Float32Array(n*3),3));hitGeometry.setAttribute('pointSize',new THREE.Float32BufferAttribute(new Float32Array(n),1));
 hitMesh=new THREE.Points(hitGeometry,new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:false,vertexColors:true,uniforms:{pixelRatio:{value:renderer.getPixelRatio()}},vertexShader:`attribute float pointSize; varying vec3 vColor; varying float vSize; uniform float pixelRatio; void main(){vColor=color;vSize=pointSize;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);gl_PointSize=max(.1,pointSize*pixelRatio);}`,fragmentShader:`varying vec3 vColor; varying float vSize; void main(){if(vSize<1.)discard;float r=length(gl_PointCoord-.5)*2.;if(r>1.)discard;float a=smoothstep(1.,.15,r);gl_FragColor=vec4(vColor,a);}`}));hitMesh.frustumCulled=false;hitMesh.renderOrder=10;scene.add(hitMesh);
 new ResizeObserver(resize).observe(stage);resize();requestAnimationFrame(animate);
}
function buildGeology(){const surface=geo.surface_z, bedrock=geo.bedrock_z, width=1900;
 const iceBox=new THREE.BoxGeometry(width,width,surface-bedrock);const ice=new THREE.Mesh(iceBox,new THREE.MeshBasicMaterial({color:0x5eaccd,transparent:true,opacity:.022,depthWrite:false,side:THREE.DoubleSide}));ice.position.z=(surface+bedrock)/2;geology.add(ice);
 const edges=new THREE.LineSegments(new THREE.EdgesGeometry(iceBox),new THREE.LineBasicMaterial({color:0x5f9bb7,transparent:true,opacity:.17}));edges.position.copy(ice.position);geology.add(edges);
 const rock=new THREE.Mesh(new THREE.BoxGeometry(width,width,200),new THREE.MeshBasicMaterial({color:0x8f7564,transparent:true,opacity:.11,depthWrite:false}));rock.position.z=bedrock-100;geology.add(rock);
 const dustSlab=new THREE.Mesh(new THREE.BoxGeometry(width,width,100),new THREE.MeshBasicMaterial({color:0xbaa080,transparent:true,opacity:.055,depthWrite:false}));dustSlab.position.z=surface-2050;dust.add(dustSlab);
 geology.userData.labels=new THREE.Group();geology.add(geology.userData.labels);for(const [label,z] of [['Surface',surface],['Ice · 2,810 m',(surface+bedrock)/2],['Bedrock',bedrock]])geology.userData.labels.add(textLabel(label,[-1050,0,z]));dust.userData.label=textLabel('Dust band · schematic',[-1050,0,surface-2050]);dust.add(dust.userData.label);
}
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
function view(mode){for(const id of ['focus','detector','ice']){const button=$(`${id}-view`);button.classList.toggle('selected',id===mode);button.setAttribute('aria-pressed',String(id===mode));}if(mode==='focus'&&current){orbit.target.copy(V(current.primary.pos));orbit.radius=950;}else if(mode==='ice'){orbit.target.set(0,0,(geo.surface_z+geo.bedrock_z)/2);orbit.radius=5100;}else{orbit.target.set(0,0,-60);orbit.radius=2250;}orbit.phi=1.12;}
function isFiniteVector(v){return Array.isArray(v)&&v.length===3&&v.every(Number.isFinite);}
function trackParticles(event){return event.truth.filter((p,i)=>[11,13,15].includes(Math.abs(p.pdg))&&p.shape!=='Dark'&&Number.isFinite(p.length)&&p.length>0&&Number.isFinite(p.speed)&&p.speed>0&&Number.isFinite(p.time)&&isFiniteVector(p.pos)&&isFiniteVector(p.dir)&&!event.truth.some(c=>c.parent===i&&c.pdg===p.pdg&&c.length>0&&c.shape!=='Dark'));}
function buildTruth(){disposeGroup(truth);disposeGroup(guide);actors=[];const p=current.primary, start=V(p.pos), direction=V(p.dir);
 const guideStart=start.clone().addScaledVector(direction,-240), guideEnd=start.clone().addScaledVector(direction,75);
 guide.add(line([guideStart.toArray(),guideEnd.toArray()],0xd5dce5,.6,true));const arrow=new THREE.ArrowHelper(direction,start.clone().addScaledVector(direction,-25),25,0xd5dce5,10,6);guide.add(arrow);
 const vertex=points([p.pos],0xffffff,7,1);vertex.userData.start=p.time;truth.add(vertex);actors.push({kind:'point',object:vertex,time:p.time});
 for(const particle of trackParticles(current)){const endpoint=V(particle.pos).addScaledVector(V(particle.dir),particle.length);const path=line([particle.pos,endpoint.toArray()],0xa5f2dd,1);truth.add(path);actors.push({kind:'track',object:path,particle,end:endpoint});}
 const cascades=current.truth.filter(q=>q.shape==='Cascade'&&isFiniteVector(q.pos)&&Number.isFinite(q.time));
 for(const q of cascades){const point=points([q.pos],0xffe5b0,4,.7);truth.add(point);actors.push({kind:'point',object:point,time:q.time});}
 const missing=current.truth.filter(q=>[11,13,15].includes(Math.abs(q.pdg))&&q.shape!=='Dark'&&!(Number.isFinite(q.length)&&q.length>0));
 $('truth-note').textContent=missing.length?'Some lepton lengths are absent in this MC. Their paths are not inferred.':'Solid line: stored lepton path. Dashed line: ν direction guide.';
}
function updateHits(){if(!current)return;const time=tmin+fraction*(tmax-tmin), sizes=hitGeometry.attributes.pointSize.array, colors=hitGeometry.attributes.color.array;sizes.fill(0);let shown=0;const charges=new Float64Array(geo.modules.length), first=new Float64Array(geo.modules.length);first.fill(Infinity);
 for(const pulse of current.pulses){if(pulse[1]>time)break;const module=geo.channels[pulse[0]][0];charges[module]+=pulse[2];first[module]=Math.min(first[module],pulse[1]);shown++;}
 for(let i=0;i<charges.length;i++){if(!Number.isFinite(first[i])||!$(`show-${geo.modules[i][6]}`).checked)continue;const u=(first[i]-tmin)/(tmax-tmin);dummyColor.setHSL(.035+.62*u,.9,.59);dummyColor.toArray(colors,i*3);sizes[i]=Math.min(24,4+3*Math.sqrt(Math.max(0,charges[i])));}
 hitGeometry.attributes.pointSize.needsUpdate=true;hitGeometry.attributes.color.needsUpdate=true;
 for(const actor of actors){if(actor.kind==='point'){actor.object.visible=time>=actor.time;continue;}const p=actor.particle;const f=Math.max(0,Math.min(1,(time-p.time)*p.speed/p.length));actor.object.visible=f>0;const end=V(p.pos).lerp(actor.end,f);actor.object.geometry.attributes.position.setXYZ(1,end.x,end.y,end.z);actor.object.geometry.attributes.position.needsUpdate=true;actor.object.geometry.computeBoundingSphere();}
 $('time').textContent=`${((time-current.primary.time)/1000).toFixed(2)} µs`;$('pulse-count').textContent=`${shown.toLocaleString()} / ${current.pulses.length.toLocaleString()} pulses`;$('scrub').value=Math.round(fraction*1000);
}
function animate(wall){requestAnimationFrame(animate);if(playing&&current){fraction=Math.min(1,fraction+(wall-lastWall)/11000);if(fraction>=1)setPlaying(false);updateHits();}lastWall=wall;orbit.update();const labelsVisible=orbit.radius>3300;geology.userData.labels.visible=labelsVisible;dust.userData.label.visible=labelsVisible;const metresPerPixel=2*orbit.radius*Math.tan(camera.fov*Math.PI/360)/stage.clientHeight;const desired=metresPerPixel*80;const candidates=[1,2,5,10,20,50,100,200,500,1000,2000];const scale=candidates.reduce((a,b)=>Math.abs(b-desired)<Math.abs(a-desired)?b:a);$('scale').textContent=scale>=1000?`${scale/1000} km`:`${scale} m`;$('scale').style.width=`${scale/metresPerPixel}px`;renderer.render(scene,camera);}
function filterMatches(){const f=$('flavor').value,interaction=$('interaction').value,sign=$('sign').value,energy=$('energy').value,direction=$('direction').value,azimuth=$('azimuth').value;return catalogue.filter(e=>(!f||Math.abs(e.pdg)===+f)&&(!interaction||e.interaction===+interaction)&&(!sign||Math.sign(e.pdg)===+sign)&&(energy===''||e.cell[2]===+energy)&&(direction===''||e.cell[3]===+direction)&&(azimuth===''||e.cell[4]===+azimuth));}
async function applyFilters(){matches=filterMatches();currentIndex=0;for(const id of ['previous','next','random'])$(id).disabled=!matches.length;if(!matches.length){generation++;setPlaying(false);current=null;disposeGroup(truth);disposeGroup(guide);hitGeometry.attributes.pointSize.array.fill(0);hitGeometry.attributes.pointSize.needsUpdate=true;$('event-type').textContent='No sampled event';$('event-values').textContent='Try a wider energy or direction range.';$('match-count').textContent='0 events in this selection';$('event-id').textContent='';$('pulse-count').textContent='';$('time').textContent='—';$('truth-note').textContent='Empty cells are preserved; no synthetic events are added.';$('play').textContent='▶';$('start-time').textContent='—';$('end-time').textContent='—';history.replaceState(null,'',location.pathname);document.body.classList.remove('loading');return;}await loadEvent(matches[0]);}
async function loadEvent(entry){const request=++generation;setPlaying(false);document.body.classList.add('loading');try{const event=await getJSON(`data/events/${entry.id}.json`);if(request!==generation)return;current=event;currentIndex=matches.findIndex(x=>x.id===entry.id);fraction=1;const tracks=trackParticles(event);const times=[event.primary.time,...event.pulses.map(p=>p[1]),...tracks.flatMap(p=>[p.time,p.time+p.length/p.speed])];tmin=Math.min(...times);tmax=Math.max(...times);if(tmax===tmin)tmax=tmin+1;buildTruth();updateHits();view('focus');const p=event.primary;const name=`${p.pdg<0?'anti-':''}${LABELS[Math.abs(p.pdg)]} · ${event.interaction===1?'CC':'NC'}`;$('event-type').textContent=name;$('event-values').textContent=`${p.energy.toFixed(1)} GeV   ·   zenith ${(event.zenith*180/Math.PI).toFixed(1)}°\nazimuth ${(event.azimuth*180/Math.PI).toFixed(1)}°   ·   depth ${((geo.surface_z-p.pos[2])/1000).toFixed(2)} km`;$('event-id').textContent=event.id;$('match-count').textContent=`${currentIndex+1} / ${matches.length.toLocaleString()} matching events`;$('start-time').textContent=`${((tmin-p.time)/1000).toFixed(1)} µs`;$('end-time').textContent=`${((tmax-p.time)/1000).toFixed(1)} µs`;history.replaceState(null,'',`#event=${event.id}`);updateDetails();}catch(error){if(request===generation)fail(error);}finally{if(request===generation)document.body.classList.remove('loading');}}
function updateDetails(){if(!current)return;const p=current.primary,rows=[['Event',current.id],['MC file',current.source],['Dataset',current.dataset],['Primary PDG',p.pdg],['Interaction',current.interaction===1?'CC':'NC'],['Energy',`${p.energy.toPrecision(9)} GeV`],['Direction',`cos θ = ${current.coszen.toFixed(6)}; azimuth ${(current.azimuth*180/Math.PI).toFixed(3)}°`],['Vertex',`${p.pos.map(x=>x.toFixed(3)).join(', ')} m (GCD x, y, z)`],['Pulses',`${current.pulses.length}; ${new Set(current.pulses.map(p=>p[0])).size} PMT channels`],['Stored lepton segments',trackParticles(current).length],['Truth particles',current.truth.length],['GCD',geo.source],['Ice thickness',`${geo.surface_z-geo.bedrock_z} m`]];const table=document.createElement('table');for(const [key,value] of rows){const row=table.insertRow();const head=document.createElement('th');head.textContent=key;row.append(head);row.insertCell().textContent=value;}$('detail-content').replaceChildren(table);$('event-download').href=`data/events/${current.id}.json`;}
function bindUI(){for(const id of ['flavor','interaction','sign','energy','direction','azimuth'])$(id).onchange=()=>applyFilters().catch(fail);for(const sub of SUBS)$(`show-${sub}`).onchange=e=>{detectors[sub].visible=e.target.checked;updateHits();};$('show-truth').onchange=e=>truth.visible=e.target.checked;$('show-guide').onchange=e=>guide.visible=e.target.checked;$('show-ice').onchange=e=>{geology.visible=e.target.checked;dust.visible=e.target.checked&&$('show-dust').checked;};$('show-dust').onchange=e=>dust.visible=e.target.checked&&$('show-ice').checked;for(const mode of ['focus','detector','ice'])$(`${mode}-view`).onclick=()=>view(mode);$('random').onclick=()=>{if(matches.length>1)currentIndex=(currentIndex+1+Math.floor(Math.random()*(matches.length-1)))%matches.length;loadEvent(matches[currentIndex]);};$('previous').onclick=()=>loadEvent(matches[(currentIndex-1+matches.length)%matches.length]);$('next').onclick=()=>loadEvent(matches[(currentIndex+1)%matches.length]);$('play').onclick=()=>{if(!current)return;setPlaying(!playing);if(playing&&fraction>=1)fraction=0;lastWall=performance.now();updateHits();};$('scrub').oninput=e=>{setPlaying(false);fraction=+e.target.value/1000;updateHits();};$('details').onclick=()=>{if(current)$('detail-dialog').showModal();};$('close-details').onclick=()=>$('detail-dialog').close();$('share').onclick=async()=>{if(!current)return;try{await navigator.clipboard.writeText(location.href);$('share').textContent='Copied';setTimeout(()=>$('share').textContent='Copy link',1800);}catch{$('share').textContent='Copy the address bar';}};}
async function main(){[geo,catalogue,metadata]=await Promise.all(['geometry','catalogue','metadata'].map(n=>getJSON(`data/${n}.json`)));$('library-count').textContent=`${catalogue.length.toLocaleString()} events`;initScene();bindUI();const id=new URLSearchParams(location.hash.slice(1)).get('event'),entry=catalogue.find(e=>e.id===id);if(entry){$('flavor').value=Math.abs(entry.pdg);$('interaction').value=entry.interaction;$('sign').value=Math.sign(entry.pdg);$('energy').value=entry.cell[2];matches=filterMatches();await loadEvent(entry);}else await applyFilters();window.mcViewer={get state(){return{event:current?.id,eventCount:catalogue.length,matching:matches.length,pulses:current?.pulses.length,segments:current?trackParticles(current).length:0,fraction,playing};}};}
main().catch(fail);
